import cv2 as cv
import numpy as np
img=cv.imread("Photos/park.jpg")
blank=np.zeros(img.shape[:2],dtype="uint8")
b,g,r=cv.split(img)
cv.imshow("Blue ",b)
cv.imshow("Green ",g)
cv.imshow("Red ",r)
blue=cv.merge([b,blank,blank])
green=cv.merge([blank,g,blank])
red=cv.merge([blank,blank,r])
print(b.shape)
print(r.shape)
print(g.shape)
print(img.shape)
cv.imshow("Blue ",blue)
cv.imshow("Green ",green)
cv.imshow("Red ",red)
cv.waitKey(0)
cv.destroyAllWindows()
