import cv2 as cv
import numpy as np
img=cv.imread("cats.jpg")
blank=np.zeros(img.shape[:2],dtype="float32")
cv.imshow("Cat",img)
grey=cv.cvtColor(img,cv.COLOR_BGR2GRAY)
# cv.imshow("Grey cat",grey)
blur=cv.blur(img,(5,5),cv.BORDER_DEFAULT)
# cv.imshow('blur',blur)
canny=cv.Canny(blur,125,175)
cv.imshow('canny',canny)
r,thresh=cv.threshold(canny,125,255,cv.THRESH_BINARY)
# cv.imshow("Thresh",thresh)
contour,hr=cv.findContours(canny,cv.RETR_LIST,cv.CHAIN_APPROX_SIMPLE)
print(f'{len(contour)} is the length of the list')
draw=cv.drawContours(blank,contour,-1,(255,255,255),2)
cv.imshow("Contours using canny",draw)
contour,hr=cv.findContours(thresh,cv.RETR_LIST,cv.CHAIN_APPROX_SIMPLE)
print(f'{len(contour)} is the length of the list')
# draw=cv.drawContours(blank,contour,-1,(255,255,255),2)
# cv.imshow("Contours using Thresh",draw)
cv.waitKey()